libwir_la_SOURCES      += analyses/reachability/wirreachabilityanalysis.cc analyses/reachability/wirreachabilityanalysis.h

if !WITH_RESTRICTED_INSTALL
  areachincludedir	= ${includedir}/analyses/reachability

  areachinclude_HEADERS	= analyses/reachability/wirreachabilityanalysis.h
endif
