libwir_la_SOURCES      += arch/tricore/optimizations/redundantcode/tcredundantcode.cc arch/tricore/optimizations/redundantcode/tcredundantcode.h

if !WITH_RESTRICTED_INSTALL
  otcrcincludedir	= ${includedir}/arch/tricore/optimizations/redundantcode

  otcrcinclude_HEADERS= arch/tricore/optimizations/redundantcode/tcredundantcode.h
endif
