libwir_la_SOURCES      += arch/tricore/optimizations/deadcode/tcdeadcode.cc arch/tricore/optimizations/deadcode/tcdeadcode.h

if !WITH_RESTRICTED_INSTALL
  otcdceincludedir	= ${includedir}/arch/tricore/optimizations/deadcode

  otcdceinclude_HEADERS = arch/tricore/optimizations/deadcode/tcdeadcode.h
endif
