libwir_la_SOURCES      += analyses/immediatedomination/wirimmediatedominationanalysis.cc analyses/immediatedomination/wirimmediatedominationanalysis.h

if !WITH_RESTRICTED_INSTALL
  aidomaincludedir	= ${includedir}/analyses/immediatedomination

  aidomainclude_HEADERS	= analyses/immediatedomination/wirimmediatedominationanalysis.h
endif
