libwir_la_SOURCES      += optimizations/constfold/wirconstfold.cc optimizations/constfold/wirconstfold.h

if !WITH_RESTRICTED_INSTALL
  ocfincludedir		= ${includedir}/optimizations/constfold

  ocfinclude_HEADERS	= optimizations/constfold/wirconstfold.h
endif
