libwir_la_SOURCES      += arch/tricore/optimizations/operationbitwidths/tcoperationbitwidths.cc arch/tricore/optimizations/operationbitwidths/tcoperationbitwidths.h

if !WITH_RESTRICTED_INSTALL
  otcobwincludedir	= ${includedir}/arch/tricore/optimizations/operationbitwidths

  otcobwinclude_HEADERS = arch/tricore/optimizations/operationbitwidths/tcoperationbitwidths.h
endif
